Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django_registration.backends.activation.views import RegistrationView

from accounts.forms import CustomUserForm

urlpatterns = [
    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=CustomUserForm
        ),
        name='django_registration_register',
        ),

    url(r'accounts/',
        include('django_registration.backends.activation.urls')
        ),
    path('admin/', admin.site.urls),

    path(r'myaccount/', include('accounts.urls')),

    path(r'', include('posts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('<int:pk>/', views.AccountView.as_view(), name='user_account'),
    path(r'comments/', views.CommentsView.as_view(), name='user_comments'),
    # path(r'login/', views.CommentsView.as_view(), name='login'),
    # path(r'logout/', views.CommentsView.as_view(), name='logout')
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostList.as_view(), name='index'),  # get with filter
    path(r'unpublished/', views.PostList.as_view(published=False), name='unpublished_posts'),
    path(r'post/create/', views.CreatePostView.as_view(), name='create_post'),  # post - in that page
    path(r'post/<int:post_id>/', views.PostView.as_view(), name='view_post'),  # get
    path(r'post/<int:post_id>/preview/', views.PostPreviewView.as_view(), name='preview_post'),  # get?? method preview
    path(r'post/<int:post_id>/edit/', views.UpdatePostView.as_view(), name='update_post'),  # patch - in that page
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    notice_comments = models.BooleanField(null=True)
    notice_new_posts = models.BooleanField(null=True)

posts/models.py
from datetime import timedelta
from uuid import uuid4

from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Post(models.Model):
    published = models.BooleanField(default=False)
    date = models.DateTimeField('Date published')
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


def get_path_to_upload(instance, filename):
    ext = filename.split('.')[-1]  # may loaded other ext?
    filename = "%s.%s" % (uuid4(), ext)
    return 'post_{0}/{1}'.format(instance.post.id, filename)


def get_deleted_user():
    del_user, created = get_user_model().objects.get_or_create(username="Deleted user", password='deletedUser')
    return del_user.id


class ImagesFromPost(models.Model):
    post = models.ForeignKey(Post, on_delete='CASCADE')
    image = models.ImageField(upload_to=get_path_to_upload)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete='CASCADE')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_DEFAULT,
        default=get_deleted_user,
    )
    date = models.DateTimeField('Date published')
    content = models.TextField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE)

    def __str__(self):
        return self.author.name + " " + self.post.title

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Category(models.Model):
    posts = models.ManyToManyField(Post)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

accounts/forms.py
from django_registration.forms import RegistrationForm
from django.contrib.auth import get_user_model
#from .models import User


class CustomUserForm(RegistrationForm):
    # TODO: add required fields to reg form

    class Meta(RegistrationForm.Meta):
        model = get_user_model()
        # TODO: specify all fields from Custom user model
        #  or make mew fields with define value or null

accounts/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth import get_user_model
from posts.models import Comment


class CommentsView(ListView):
    model = Comment
    context_object_name = 'all_comment'
    template_name = 'accounts/comments.html'
    # TODO: done that with session keys for safety other users


class AccountView(DetailView):
    model = get_user_model()
    template_name = 'accounts/account.html'
    context_object_name = 'user_obj'
    # TODO: done that with session keys for safety other users
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_comments'] = Comment.objects.filter(id__lte=2)
        return context

posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, DateDetailView, FormView, UpdateView, CreateView
from django.views import View
from django.utils import timezone

from .models import Post, Comment, Category


class PostList(ListView):
    published = True
    model = Post
    template_name = 'posts/index.html'
    context_object_name = 'all_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        # TODO: how add the most popular posts by views?
        return context

    def get_queryset(self):
        return Post.objects.filter(published=self.published,
                                   date__lt=timezone.now()).order_by('-date')


class PostView(DetailView):
    model = Post
    context_object_name = 'post'


class PostPreviewView(DetailView):
    model = Post
    context_object_name = 'post'


class CreatePostView(CreateView):
    model = Post
    fields = ['published', 'date', 'title', 'content']
    template_name = 'post_form.html'


class UpdatePostView(UpdateView):
    model = Post
    fields = ['published', 'date', 'title', 'content']
    template_name = 'post_form.html'


# TODO: change directory with templates to turn correct reusable static

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "fontawesome/css/all.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% block additional_styles %}{% endblock %}
</head>
<body>

{% include 'header.html' %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/django_registration/activation_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activation complete</title>
    <link rel="stylesheet" href="registration.css">
</head>
<body>
<section class="activation_complete">
    <div>
        <p>Congratulations, activation is successfully completed!</p>
        <p>Link <a href="">here</a> to redirect to login page</p>
        <a href="#" class="back_main btn_act">Back to main</a>
    </div>
</section>
</body>
</html>

templates/django_registration/activation_failed.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activation failed</title>
    <link rel="stylesheet" href="{% static "css/registration/registration.css" %}">
</head>
<body>
<section class="activation_failed">
    <div>
        <p>Oops, something is wrong...</p>
        <p>The problem is: <span class="error">{{ activation_error }}</span></p>
        <a href="{% url "index" %}" class="back_main btn_fail">Back to main</a>
    </div>
</section>
</body>
</html>

templates/django_registration/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static "css/registration/registration_form.css" %}">
</head>
<body>
    <div class="form_login">
    <h1>Login</h1>
    <form method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="form_element">
                {{ field }}
                <div class="label-box">
                    {{ field.label_tag }}
                </div>
               {% if field.errors %}
                    <div class="error_field">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
    <div class="form_element">
        <input type="submit" class="login_user" value="Login">
        <a href="{% url "posts:index" %}" class="back_main">Back to main</a>
    </div>
    </form>
</div>
</body>
</html>

templates/django_registration/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<section class="logout">
    <div>
        <p>See you again!</p>
        <a href="{% url "index" %}" class="back_main btn_act">Back to main</a>
    </div>
</section>
</body>
</html>

templates/django_registration/registration_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration complete</title>
    <link rel="stylesheet" href="{% static "css/registration/registration.css" %}">
</head>
<body>
<section class="registration_complete">
    <div>
        <p>Congratulations, registration is successfully completed!</p>
        <p>Check your email to finish activating account.</p>
        <a href="{% url "index" %}" class="back_main btn_reg">Back to main</a>
    </div>
</section>
</body>
</html>

templates/django_registration/registration_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static "css/registration/registration_form.css" %}">
</head>
<body>
<div class="form_reg">
    <h1>Registration</h1>
    <form method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="form_element">
                {{ field }}
                <div class="label-box">
                    {{ field.label_tag }}
                </div>
                {% if field.errors %}
                    <div class="error_field">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
    <div class="form_element">
        <input type="submit" class="reg_user" value="Sign up">
        <a href="{% url "posts:index" %}" class="back_main">Back to main</a>
    </div>
    </form>
</div>
</body>
</html>

templates/footer.html
<footer>
    <section class="about_blog">
        Tatiana Maltseva, 2019 
    </section>
    <section class="copyright">
        <div>template from: <a href="#">Euciclid</a></div>
        <div>
            Icons made by <a href="https://www.flaticon.com/authors/good-ware" title="Good Ware">Good Ware</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"  title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
        </div>
    </section>
</footer>

templates/header.html
{% load static %}
<header class="main_header">
    <div class="logo">
        <img src="{% static 'image/email.png' %}" alt="logo">
    </div>
    <nav>
        <ul>
            <li><a href="#">Main</a></li>
            <li><a href="#">Login</a></li>
        </ul>
    </nav>
</header>