posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostList.as_view(), name='index'),  # get with filter
    path(r'unpublished/', views.PostList.as_view(published=False), name='unpublished_posts'),
    path(r'post/create/', views.CreatePostView.as_view(), name='create_post'),  # post - in that page
    path(r'post/<int:post_id>/', views.PostView.as_view(), name='view_post'),  # get
    path(r'post/<int:post_id>/preview/', views.PostPreviewView.as_view(), name='preview_post'),  # get?? method preview
    path(r'post/<int:post_id>/edit/', views.UpdatePostView.as_view(), name='update_post'),  # patch - in that page
]

posts/models.py
from datetime import timedelta
from uuid import uuid4

from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Post(models.Model):
    published = models.BooleanField(default=False)
    date = models.DateTimeField('Date published')
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


def get_path_to_upload(instance, filename):
    ext = filename.split('.')[-1]  # may loaded other ext?
    filename = "%s.%s" % (uuid4(), ext)
    return 'post_{0}/{1}'.format(instance.post.id, filename)


def get_deleted_user():
    del_user, created = get_user_model().objects.get_or_create(username="Deleted user", password='deletedUser')
    return del_user.id


class ImagesFromPost(models.Model):
    post = models.ForeignKey(Post, on_delete='CASCADE')
    image = models.ImageField(upload_to=get_path_to_upload)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete='CASCADE')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_DEFAULT,
        default=get_deleted_user,
    )
    date = models.DateTimeField('Date published')
    content = models.TextField()
    parent = models.ForeignKey('self', on_delete=models.CASCADE)

    def __str__(self):
        return self.author.name + " " + self.post.title

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Category(models.Model):
    posts = models.ManyToManyField(Post)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, DateDetailView, FormView, UpdateView, CreateView
from django.views import View
from django.utils import timezone

from .models import Post, Comment, Category


class PostList(ListView):
    published = True
    model = Post
    template_name = 'posts/index.html'
    context_object_name = 'all_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        # TODO: how add the most popular posts by views?
        return context

    def get_queryset(self):
        return Post.objects.filter(published=self.published,
                                   date__lt=timezone.now()).order_by('-date')


class PostView(DetailView):
    model = Post
    context_object_name = 'post'


class PostPreviewView(DetailView):
    model = Post
    context_object_name = 'post'


class CreatePostView(CreateView):
    model = Post
    fields = ['published', 'date', 'title', 'content']
    template_name = 'post_form.html'


class UpdatePostView(UpdateView):
    model = Post
    fields = ['published', 'date', 'title', 'content']
    template_name = 'post_form.html'


# TODO: change directory with templates to turn correct reusable static

posts/templates/posts/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Welcome to blog!{% endblock %}

{% block content %}
    <section class="warning_unpublished">
    <p>Warning! You are on the page with unpublished posts!</p>
</section>
<main>
    <section class="articles">
        {% for post in all_posts %}
        <article>
            <header class="article_header">
                <h1 class="post_head">
                    <a href="#">{{ post.title }}</a>
                </h1>
                <div class="status">
                    <time class="date">{{ post.date|date:"j F, H:i" }}</time>
                    <span class="post_categories">
                        {% for category in post.category_set.all %}
                            <a href="#{{ category.id }}">
                                {{ category.name }}{% if not forloop.last %},{% endif %}
                            </a>
                        {% endfor %}
                    </span>
                    <span class="comments">No comments</span>
                </div>
            </header>
            <img src="{% static 'image/2.jpeg' %}" alt="image post" class="article_img">
            <div class="description">
                {{ post.content }}
            </div>
            <a href="#" class="readmore">Read more</a>
        </article>
        {% endfor %}
        <div class="paginator">
            <a href="#1">1</a>
            <span>&hellip;</span>
            <a href="#3">3</a>
            <a href="#4">10</a>
        </div>
    </section>
    <aside>
        <div class="search">
            <form action="" class="search_form">
                <input type="text" name="search" id="">
                <button type="submit" class="searchbutton">Search</button>
            </form>
        </div>
        <section class="categories">
            <h3 class="head">Categories</h3>
            <ul>
                {% for category in categories %}
                    <li><a href="">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </section>

    </aside>
</main>
{% endblock %}

posts/templates/posts/post.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static "css/post.css" %}">
{% endblock %}

{%  block content %}
<main>
    <section class="article_full">
        <article>
            <header class="article_header">
                <h1 class="post_head"><a href="#">{{ post.title }}</a></h1>
                <div class="status">
                    <time class="date">{{ post.date|date:"j F, H:i" }}</time>
                    <span class="post_categories">
                        {% for category in post.category_set.all %}
                            <a href="#{{ category.id }}">
                                {{ category.name }}{% if not forloop.last %},{% endif %}
                            </a>
                        {% endfor %}
                    </span>
                    <span class="comments">No comments</span>
                </div>
            </header>
            <img src="{% static 'image/2.jpeg' %}" alt="image post" class="article_img">
            <div class="description">
                {{ post.content }}

                At commodi culpa cumque ex hic ipsam iusto libero magnam minima molestiae odio officia omnis porro
                    provident quisquam rerum similique temporibus tenetur, veritatis vero. Amet reiciendis sapiente sed
                    veritatis vitae?

                Adipisci aliquid, architecto assumenda delectus, ducimus eligendi esse et excepturi fuga inventore ipsa
                    magni molestiae molestias mollitia neque omnis praesentium quam quas quis quos repudiandae similique
                    tempora ullam unde voluptas.

                Accusamus consectetur cumque distinctio doloribus eligendi, ex, harum placeat quasi qui repellat sed
                    tenetur velit voluptatibus! Asperiores aut consectetur, delectus ea in ipsam, laudantium nemo, numquam
                    praesentium quasi quis totam?

            </div>
            <a href="" class="readmore">Read more</a>
        </article>

        <div class="warning_guest">
            Sorry, but only registered users can add comments. You can sign up <a href="#">here</a>.
        </div>

        <div class="form_comment_wrapper">
            <h3 class="first_comment_header">Your comment</h3>
            <!--No Comments, Be The First!-->
            <form action="" class="add_comment">
                <textarea name="text_comment" id="text_comment" placeholder="Enter message here"></textarea>
                <input type="submit" value="Send comment" class="send_comment">
            </form>
        </div>

        <section class="list_comments">
            <ul>
                <li class="comment_card">
                    <div class="comment_header">
                        <span class="author_name">Tatiana Maltseva</span>
                        <span class="date_comment">19 March 2019, 15:27</span>
                    </div>
                    <div class="comment_body">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Atque ducimus eaque, eos eveniet fugit pariatur. Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit.
                        Atque ducimus eaque, eos eveniet fugit pariatur.</div>
                </li>
                <li class="comment_card">
                    <div class="comment_header">
                        <span class="author_name admin">Tatiana Maltseva</span>
                        <span class="date_comment">19 March 2019, 15:27</span>
                    </div>
                    <div class="comment_body">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Atque ducimus eaque, eos eveniet fugit pariatur.</div>
                </li>
                <li class="comment_card">
                    <div class="comment_header">
                        <span class="author_name">Tatiana Maltseva</span>
                        <span class="date_comment">19 March 2019, 15:27</span>
                    </div>
                    <div class="comment_body">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Atque ducimus eaque, eos eveniet fugit pariatur.</div>
                </li>
            </ul>
        </section>
    </section>

    <aside>
        <div class="search">
            <form action="" class="search_form">
                <input type="text" name="search" id="">
                <button type="submit" class="searchbutton">Search</button>
            </form>
        </div>
        <section class="categories">
            <h3 class="head">Categories</h3>
            <ul>
                {% for category in categories %}
                    <li><a href="">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </section>

    </aside>
</main>

{% endblock %}

posts/templates/posts/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form to create or edit post</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <!-- below will changed by context -->
<input type="submit" value="Update">
</form>
</body>
</html>